name: Agada Dotnet CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2019

    name: Dotnet Build & Test
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet 1.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '1.1.x'

      - name: Setup dotnet 2.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.0.x'

      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup dotnet 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - run: dotnet build -c Release ./src/Agada
      - run: dotnet test Test -f netcoreapp1.1 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f netcoreapp2.0 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f netcoreapp3.1 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f netcoreapp5.0 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f net6.0 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f net7.0 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f net8.0 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f net45 ./src/Agada/Agada.csproj
      - run: dotnet test Test -f net462 ./src/Agada/Agada.csproj
